# Generated by Django 3.2.9 on 2021-11-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_system', '0002_auto_20211115_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата старта'),
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True, verbose_name='Уникальный номер пользователя')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_system.survey', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=500, verbose_name='Ответ')),
                ('passing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_system.passing', verbose_name='Прохождение опроса')),
            ],
        ),
    ]
