# Generated by Django 3.2.9 on 2021-11-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_system', '0003_auto_20211115_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='passing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey_system.passing', verbose_name='Прохождение опроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_system.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey_system.survey'),
        ),
    ]
